In [101]:
import numpy as np
import pandas as pd

In [102]:
df = pd.read_csv('creditcarddata.csv')

In [103]:
df.head()

,time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,amount,class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [104]:
df.shape

(772, 31)

In [105]:
class_count_0, class_count_1 = df['class'].value_counts()
class_count_0, class_count_1

(763, 9)

In [106]:
class_0 = df[df['class'] == 0]
class_1 = df[df['class'] == 1]
class_0.shape, class_1.shape

((763, 31), (9, 31))

In [107]:
X = df.iloc[:, 1:-1]
y = df.iloc[:, -1]

In [108]:
X

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,amount
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,-0.572263,0.731748,1.541254,0.150506,1.108974,0.372152,1.084879,-0.146329,-0.274447,-0.663670,...,0.056544,-0.143508,-0.107582,-0.418263,-0.731029,0.877525,-0.364150,-0.177509,-0.256545,26.72
768,-1.296845,-0.511605,2.404726,-0.310762,-0.319551,-0.542842,-0.173310,0.260423,-1.202688,0.050584,...,-0.349668,-0.071270,-0.161175,0.088496,0.285390,0.281069,-0.370130,0.043410,0.092318,80.00
769,1.214170,0.210481,0.484651,0.479768,-0.261955,-0.527039,0.021782,-0.106888,-0.037631,-0.144073,...,-0.071540,-0.224292,-0.594609,0.159877,0.091873,0.140964,0.227406,-0.017389,0.016030,5.98
770,1.267030,-0.071114,0.037680,0.512683,0.242392,0.705212,-0.226582,0.109483,0.657565,-0.276918,...,-0.066990,-0.164468,-0.177225,-0.222918,-1.245505,0.678360,0.525059,0.002920,-0.003333,12.36
771,1.153758,0.132273,0.382969,1.405063,-0.224287,-0.197295,0.020653,0.029260,0.412254,-0.103547,...,-0.230877,-0.107809,-0.125231,-0.057041,0.073082,0.633977,-0.310685,0.033590,0.015250,13.79

In [109]:
y

0      0
1      1
2      0
3      0
4      0
      ..
767    0
768    0
769    0
770    0
771    0
Name: class, Length: 772, dtype: int64

In [110]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state = 42)
x_ros, y_ros = ros.fit_resample(X, y)

In [111]:
from collections import Counter
Counter(y), Counter(y_ros)

(Counter({0: 763, 1: 9}), Counter({0: 763, 1: 763}))

In [112]:
dataset = pd.concat([x_ros.reset_index(drop=True),y_ros.reset_index(drop=True)], axis=1)
dataset

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,amount,class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,-2.000567,-2.495484,2.467149,1.140053,2.462010,0.594262,-2.110183,0.788347,0.958809,-0.328631,...,0.422452,1.195394,0.297836,-0.857105,-0.219322,0.861019,-0.124622,-0.171060,1.50,1
1522,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
1523,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
1524,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,-0.066407,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1
1525,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,-0.838587,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1

In [113]:
size1 = 305
n = dataset.shape[0]
interval = (n // size1)

In [114]:
# sample 1 - Systematic random sampling
import random
random_number = random.randint(0, interval)
def systematic_sampling(df, step):
    indexes = np.arange(random_number, len(df), step=step)
    systematic_sample = df.iloc[indexes]
    return systematic_sample

In [115]:
sample1 = systematic_sampling(dataset, interval)
sample1

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,amount,class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
5,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
10,1.449044,-1.176339,0.913860,-1.375667,-1.971383,-0.629152,-1.423236,0.048456,-1.720408,1.626659,...,-0.009302,0.313894,0.027740,0.500512,0.251367,-0.129478,0.042850,0.016253,7.80,0
15,-0.752417,0.345485,2.057323,-1.468643,-1.158394,-0.077850,-0.608581,0.003603,-0.436167,0.747731,...,0.499625,1.353650,-0.256573,-0.065084,-0.039124,-0.087086,-0.180998,0.129394,15.99,0
20,0.694885,-1.361819,1.029221,0.834159,-1.191209,1.309109,-0.878586,0.445290,-0.446196,0.568521,...,-0.295583,-0.571955,-0.050881,-0.304215,0.072001,-0.422234,0.086553,0.063499,231.71,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,1.254914,0.350287,0.302488,0.693114,-0.371470,-1.070256,0.086781,-0.202836,0.035154,-0.282617,...,-0.287592,-0.832682,0.128083,0.339427,0.215944,0.094704,-0.023354,0.030892,2.69,1
1510,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
1515,-0.928088,0.398194,1.741131,0.182673,0.966387,-0.901004,0.879016,-0.156590,-0.142117,-0.574775,...,0.066353,0.281378,-0.257966,0.385384,0.391117,-0.453853,-0.104448,-0.125765,1.00,1
1520,1.257719,0.364739,0.306923,0.690638,-0.357792,-1.067481,0.094272,-0.210300,0.014455,-0.286012,...,-0.286856,-0.820658,0.127663,0.343128,0.221120,0.094391,-0.022189,0.030944,1.29,1
1525,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,-0.838587,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1

In [116]:
from sklearn.model_selection import train_test_split
X = sample1.iloc[:, :-1].values
y = sample1.iloc[:, -1].values

In [117]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 42)

In [118]:
# model 1 : Logistic Regression
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(X_train, y_train)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [119]:
y_pred = model1.predict(X_test)

In [120]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8455284552845529

In [121]:
# model 2 : SVM
from sklearn.svm import SVC
model2 = SVC()
model2.fit(X_train, y_train)

SVC()

In [122]:
y_pred = model2.predict(X_test)
accuracy_score(y_test, y_pred)

0.6504065040650406

In [123]:
# model 3 : Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [124]:
y_pred = model3.predict(X_test)
accuracy_score(y_test, y_pred)

0.943089430894309

In [125]:
# model 4 : Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
model4 = GaussianNB()
model4.fit(X_train, y_train)

GaussianNB()

In [126]:
y_pred = model4.predict(X_test)
accuracy_score(y_test, y_pred)

0.6991869918699187

In [127]:
# model 5 : K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
model5 = KNeighborsClassifier()
model5.fit(X_train, y_train)

KNeighborsClassifier()

In [128]:
y_pred = model5.predict(X_test)
accuracy_score(y_test, y_pred)

0.8617886178861789

In [129]:
# sample 2 - Stratified sampling
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.25, random_state=None, shuffle=True, stratify=y)

In [130]:
# model 1 : Logistic Regression
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(X_train, y_train)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [131]:
y_pred = model1.predict(X_test)

In [132]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8701298701298701

In [133]:
# model 2 : SVM
from sklearn.svm import SVC
model2 = SVC()
model2.fit(X_train, y_train)

SVC()

In [134]:
y_pred = model2.predict(X_test)
accuracy_score(y_test, y_pred)

0.8311688311688312

In [135]:
# model 3 : Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [136]:
y_pred = model3.predict(X_test)
accuracy_score(y_test, y_pred)

0.987012987012987

In [137]:
# model 4 : Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
model4 = GaussianNB()
model4.fit(X_train, y_train)

GaussianNB()

In [138]:
y_pred = model4.predict(X_test)
accuracy_score(y_test, y_pred)

0.7142857142857143

In [139]:
# model 5 : K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
model5 = KNeighborsClassifier()
model5.fit(X_train, y_train)

KNeighborsClassifier()

In [140]:
y_pred = model5.predict(X_test)
accuracy_score(y_test, y_pred)

0.948051948051948

In [141]:
# sample 3 - Cluster sampling (Based on amount)
data = dataset
amount_stats = data["amount"].describe()
bins = [0, amount_stats["25%"], amount_stats["75%"], data["amount"].max()]
labels = ["low", "medium", "high"]
data["amount_cluster"] = pd.cut(data["amount"], bins=bins, labels=labels, include_lowest=True)

sampled_data = data.groupby("amount_cluster").apply(lambda x: x.sample(frac=0.3, random_state=42)).reset_index(drop=True)

X = sampled_data.drop(columns=["class", "amount_cluster"]).values
y = sampled_data["class"].values

C:\Users\HP\AppData\Local\Temp\ipykernel_17240\2319259010.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sampled_data = data.groupby("amount_cluster").apply(lambda x: x.sample(frac=0.3, random_state=42)).reset_index(drop=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_17240\2319259010.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = data.groupby("amount_cluster").apply(lambda x: x.sample(frac=0.3, random_state=42)).reset_index(drop=True)

In [142]:
X

array([[-1.73858231e+00,  5.27395170e-02,  1.18705699e+00, ...,
        -3.45129311e-01, -3.83563251e-01,  1.00000000e+00],
       [-7.91993075e-01,  1.05400662e+00, -1.10012028e-01, ...,
         6.97448350e-02, -3.76208390e-02,  8.90000000e-01],
       [ 7.34967060e-02,  5.51032960e-01,  4.51890424e-01, ...,
         2.31749598e-01,  2.30170991e-01,  9.90000000e-01],
       ...,
       [-3.04354062e+00, -3.15730712e+00,  1.08846278e+00, ...,
        -2.52773123e-01,  3.57642250e-02,  5.29000000e+02],
       [-3.04354062e+00, -3.15730712e+00,  1.08846278e+00, ...,
        -2.52773123e-01,  3.57642250e-02,  5.29000000e+02],
       [-1.03835623e+00,  7.56121842e-01,  7.19941776e-01, ...,
        -9.90463900e-03,  3.88605590e-02,  6.80000000e+01]])

In [143]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0], dtype=int64)

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [145]:
# model 1 : Logistic Regression
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(X_train, y_train)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [146]:
y_pred = model1.predict(X_test)

In [147]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8869565217391304

In [148]:
# model 2 : SVM
from sklearn.svm import SVC
model2 = SVC()
model2.fit(X_train, y_train)

SVC()

In [149]:
y_pred = model2.predict(X_test)
accuracy_score(y_test, y_pred)

0.808695652173913

In [150]:
# model 3 : Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [151]:
y_pred = model3.predict(X_test)
accuracy_score(y_test, y_pred)

0.9826086956521739

In [152]:
# model 4 : Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
model4 = GaussianNB()
model4.fit(X_train, y_train)

GaussianNB()

In [153]:
y_pred = model4.predict(X_test)
accuracy_score(y_test, y_pred)

0.8

In [154]:
# model 5 : K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
model5 = KNeighborsClassifier()
model5.fit(X_train, y_train)

KNeighborsClassifier()

In [155]:
y_pred = model5.predict(X_test)
accuracy_score(y_test, y_pred)

0.9391304347826087

In [156]:
# sample 4 - Simple Random Sampling
n = 384
dataset = dataset.drop('amount_cluster', axis = 1)
sample4 = dataset.sample(n = n, random_state=42)
sample4

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,amount,class
1439,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
76,-0.549626,0.418949,1.729833,0.203065,-0.187012,0.253878,0.500894,0.251256,-0.227985,-0.576169,...,0.115062,0.418529,-0.065133,0.264981,0.003958,0.395969,0.027182,0.043506,59.99,0
1010,1.254914,0.350287,0.302488,0.693114,-0.371470,-1.070256,0.086781,-0.202836,0.035154,-0.282617,...,-0.287592,-0.832682,0.128083,0.339427,0.215944,0.094704,-0.023354,0.030892,2.69,1
660,1.255439,0.307729,0.292700,0.699873,-0.428876,-1.088456,0.043840,-0.167739,0.128854,-0.264062,...,-0.294795,-0.882126,0.136846,0.327949,0.194459,0.096516,-0.027271,0.029491,1.98,0
1132,-1.738582,0.052740,1.187057,-0.656652,0.920623,-0.291788,0.269083,0.140631,0.023464,-0.066407,...,-0.179545,-0.192036,-0.261879,-0.237477,-0.335040,0.240323,-0.345129,-0.383563,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,-2.000567,-2.495484,2.467149,1.140053,2.462010,0.594262,-2.110183,0.788347,0.958809,-0.328631,...,0.422452,1.195394,0.297836,-0.857105,-0.219322,0.861019,-0.124622,-0.171060,1.50,1
756,-0.203837,0.532747,-0.339857,-0.730934,2.728163,3.535882,0.263680,0.919169,-0.194501,-0.585054,...,-0.082087,-0.271636,-0.157778,0.989458,0.228821,-0.545156,0.058120,0.035573,12.90,0
1074,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
867,0.073497,0.551033,0.451890,0.114964,0.822947,0.251480,0.296319,0.139497,-0.123050,-0.142617,...,-0.128758,-0.381932,0.151012,-1.363967,-1.389079,0.075412,0.231750,0.230171,0.99,1
485,1.021392,0.155451,-0.312291,0.961407,0.548611,0.121816,0.525318,-0.053891,-0.686867,0.113059,...,-0.224762,-0.850712,-0.077845,-0.679775,0.484478,-0.605930,-0.005454,0.019392,105.87,0

In [157]:
X = sample4.iloc[:, :-1].values
y = sample4.iloc[:, -1].values

In [158]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [159]:
# model 1 : Logistic Regression
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(X_train, y_train)

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [160]:
y_pred = model1.predict(X_test)

In [161]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.84375

In [162]:
# model 2 : SVM
from sklearn.svm import SVC
model2 = SVC()
model2.fit(X_train, y_train)

SVC()

In [163]:
y_pred = model2.predict(X_test)
accuracy_score(y_test, y_pred)

0.6875

In [164]:
# model 3 : Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model3 = DecisionTreeClassifier()
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [165]:
y_pred = model3.predict(X_test)
accuracy_score(y_test, y_pred)

0.9791666666666666

In [166]:
# model 4 : Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
model4 = GaussianNB()
model4.fit(X_train, y_train)

GaussianNB()

In [167]:
y_pred = model4.predict(X_test)
accuracy_score(y_test, y_pred)

0.6875

In [168]:
# model 5 : K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
model5 = KNeighborsClassifier()
model5.fit(X_train, y_train)

KNeighborsClassifier()

In [169]:
y_pred = model5.predict(X_test)
accuracy_score(y_test, y_pred)

0.9166666666666666

In [170]:
# sample 5 - Bootstrap Sampling
samples = 10
bootstrap_data = [
    dataset.sample(n = 384, replace=True, random_state=i).reset_index(drop=True)
    for i in range(samples)
]

In [171]:
# model 1 - Logistic Regression
accuracies = []
for i, bootstrap_sample in enumerate(bootstrap_data):
    X = bootstrap_sample.drop(columns=["class"])
    y = bootstrap_sample["class"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i, stratify=y)

    model = LogisticRegression(max_iter=1000, random_state=i)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

np.mean(accuracies)

0.9043103448275861

In [172]:
# model 2 - SVM
accuracies = []
for i, bootstrap_sample in enumerate(bootstrap_data):
    X = bootstrap_sample.drop(columns=["class"])
    y = bootstrap_sample["class"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i, stratify=y)

    model = SVC()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

np.mean(accuracies)

0.7353448275862069

In [173]:
# model 3 - Decision Tree Classifier
accuracies = []
for i, bootstrap_sample in enumerate(bootstrap_data):
    X = bootstrap_sample.drop(columns=["class"])
    y = bootstrap_sample["class"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i, stratify=y)

    model = DecisionTreeClassifier()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

np.mean(accuracies)

0.9853448275862068

In [174]:
# model 4 - Naive Bayes Classifier
accuracies = []
for i, bootstrap_sample in enumerate(bootstrap_data):
    X = bootstrap_sample.drop(columns=["class"])
    y = bootstrap_sample["class"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i, stratify=y)

    model = GaussianNB()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

np.mean(accuracies)

0.7232758620689655

In [175]:
# model 5 - K-Nearest Neighbors
accuracies = []
for i, bootstrap_sample in enumerate(bootstrap_data):
    X = bootstrap_sample.drop(columns=["class"])
    y = bootstrap_sample["class"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i, stratify=y)

    model = KNeighborsClassifier()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

np.mean(accuracies)

0.9275862068965518